/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GameInput */

#ifndef _Included_GameInput
#define _Included_GameInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GameInput
 * Method:    getChar
 * Signature: ()V
 */
JNIEXPORT char JNICALL Java_GameInput_getChar
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
